/* eslint-disable import/no-cycle */
/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const CHECK_CODE = 'CHECK_CODE';
export const CHECK_CODE_SUCCESS = 'CHECK_CODE_SUCCESS';
export const CHECK_CODE_ERROR = 'CHECK_CODE_ERROR';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
export const LOGIN_FACEBOOK = 'LOGIN_FACEBOOK';
export const LOGIN_FACEBOOK_SUCCESS = 'LOGIN_FACEBOOK_SUCCESS';
export const LOGIN_FACEBOOK_ERROR = 'LOGIN_FACEBOOK_ERROR';
export const LOGIN_GOOGLE = 'LOGIN_GOOGLE';
export const LOGIN_GOOGLE_SUCCESS = 'LOGIN_GOOGLE_SUCCESS';
export const LOGIN_GOOGLE_ERROR = 'LOGIN_GOOGLE_ERROR';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  'MENU_CHANGE_HAS_SUB_ITEM_STATUS';

/* PRODUCTOS APP */
export const PRODUCTOS_ALMACEN_GET_LIST = 'PRODUCTOS_ALMACEN_GET_LIST';
export const PRODUCTOS_ALMACEN_GET_LIST_SUCCESS =
  'PRODUCTOS_ALMACEN_GET_LIST_SUCCESS';
export const PRODUCTOS_ALMACEN_GET_LIST_ERROR =
  'PRODUCTOS_ALMACEN_GET_LIST_ERROR';
export const PRODUCTOS_CLIENTE_GET_LIST = 'PRODUCTOS_CLIENTE_GET_LIST';
export const PRODUCTOS_CLIENTE_GET_LIST_SUCCESS =
  'PRODUCTOS_CLIENTE_GET_LIST_SUCCESS';
export const PRODUCTOS_CLIENTE_GET_LIST_ERROR =
  'PRODUCTOS_CLIENTE_GET_LIST_ERROR';
export const PRODUCTOS_NEGOCIO_GET_LIST = 'PRODUCTOS_NEGOCIO_GET_LIST';
export const PRODUCTOS_NEGOCIO_GET_LIST_SUCCESS =
  'PRODUCTOS_NEGOCIO_GET_LIST_SUCCESS';
export const PRODUCTOS_NEGOCIO_GET_LIST_ERROR =
  'PRODUCTOS_NEGOCIO_GET_LIST_ERROR';
export const PRODUCTOS_NEGOCIO_ADD_ITEM = 'PRODUCTOS_NEGOCIO_ADD_ITEM';
export const PRODUCTOS_NEGOCIO_ADD_ITEM_SUCCESS =
  'PRODUCTOS_NEGOCIO_ADD_ITEM_SUCCESS';
export const PRODUCTOS_NEGOCIO_ADD_ITEM_ERROR =
  'PRODUCTOS_NEGOCIO_ADD_ITEM_ERROR';
export const PRODUCTOS_CLIENTE_ADD_ITEM = 'PRODUCTOS_CLIENTE_ADD_ITEM';
export const PRODUCTOS_CLIENTE_ADD_ITEM_SUCCESS =
  'PRODUCTOS_CLIENTE_ADD_ITEM_SUCCESS';
export const PRODUCTOS_CLIENTE_ADD_ITEM_ERROR =
  'PRODUCTOS_CLIENTE_ADD_ITEM_ERROR';
export const PRODUCTOS_NEGOCIO_DELETE_ITEM = 'PRODUCTOS_NEGOCIO_DELETE_ITEM';
export const PRODUCTOS_NEGOCIO_DELETE_ITEM_SUCCESS =
  'PRODUCTOS_NEGOCIO_DELETE_ITEM_SUCCESS';
export const PRODUCTOS_NEGOCIO_DELETE_ITEM_ERROR =
  'PRODUCTOS_NEGOCIO_DELETE_ITEM_ERROR';
export const PRODUCTOS_PROVEEDOR_GET_LIST = 'PRODUCTOS_PROVEEDOR_GET_LIST';
export const PRODUCTOS_PROVEEDOR_GET_LIST_SUCCESS =
  'PRODUCTOS_PROVEEDOR_GET_LIST_SUCCESS';
export const PRODUCTOS_PROVEEDOR_GET_LIST_ERROR =
  'PRODUCTOS_PROVEEDOR_GET_LIST_ERROR';
export const PRODUCTOS_CLIENTE_DELETE_ITEM = 'PRODUCTOS_CLIENTE_DELETE_ITEM';
export const PRODUCTOS_CLIENTE_DELETE_ITEM_SUCCESS =
  'PRODUCTOS_CLIENTE_DELETE_ITEM_SUCCESS';
export const PRODUCTOS_CLIENTE_DELETE_ITEM_ERROR =
  'PRODUCTOS_CLIENTE_DELETE_ITEM_ERROR';
export const PRODUCTOS_CLIENTE_UPD_ITEM = 'PRODUCTOS_CLIENTE_UPD_ITEM';
export const PRODUCTOS_CLIENTE_UPD_ITEM_SUCCESS =
  'PRODUCTOS_CLIENTE_UPD_ITEM_SUCCESS';
export const PRODUCTOS_CLIENTE_UPD_ITEM_ERROR =
  'PRODUCTOS_CLIENTE_UPD_ITEM_ERROR';
export const PRODUCTOS_NEGOCIO_GET_LIST_FREE =
  'PRODUCTOS_NEGOCIO_GET_LIST_FREE';
export const PRODUCTOS_NEGOCIO_GET_LIST_FREE_SUCCESS =
  'PRODUCTOS_NEGOCIO_GET_LIST_FREE_SUCCESS';
export const PRODUCTOS_NEGOCIO_GET_LIST_FREE_ERROR =
  'PRODUCTOS_NEGOCIO_GET_LIST_FREE_ERROR';
export const PRODUCTOS_ALMACEN_UPD_ITEM = 'PRODUCTOS_ALMACEN_UPD_ITEM';
export const PRODUCTOS_ALMACEN_UPD_ITEM_SUCCESS =
  'PRODUCTOS_ALMACEN_UPD_ITEM_SUCCESS';
export const PRODUCTOS_ALMACEN_UPD_ITEM_ERROR =
  'PRODUCTOS_ALMACEN_UPD_ITEM_ERROR';
export const PRODUCTOS_ALMACEN_DELETE_ITEM = 'PRODUCTOS_ALMACEN_DELETE_ITEM';
export const PRODUCTOS_ALMACEN_DELETE_ITEM_SUCCESS =
  'PRODUCTOS_ALMACEN_DELETE_ITEM_SUCCESS';
export const PRODUCTOS_ALMACEN_DELETE_ITEM_ERROR =
  'PRODUCTOS_ALMACEN_DELETE_ITEM_ERROR';
export const PRODUCTOS_NEGOCIO_UPD_ITEM = 'PRODUCTOS_NEGOCIO_UPD_ITEM';
export const PRODUCTOS_NEGOCIO_UPD_ITEM_SUCCESS =
  'PRODUCTOS_NEGOCIO_UPD_ITEM_SUCCESS';
export const PRODUCTOS_NEGOCIO_UPD_ITEM_ERROR =
  'PRODUCTOS_NEGOCIO_UPD_ITEM_ERROR';
export const PRODUCTOS_PROVEEDOR_UPD_PRECIO_SKU_ITEM =
  'PRODUCTOS_PROVEEDOR_UPD_PRECIO_SKU_ITEM';
export const PRODUCTOS_PROVEEDOR_UPD_PRECIO_SKU_ITEM_SUCCESS =
  'PRODUCTOS_PROVEEDOR_UPD_PRECIO_SKU_ITEM_SUCCESS';
export const PRODUCTOS_PROVEEDOR_UPD_PRECIO_SKU_ITEM_ERROR =
  'PRODUCTOS_PROVEEDOR_UPD_PRECIO_SKU_ITEM_ERROR';
export const PRODUCTOS_MARCA_GET_LIST = 'PRODUCTOS_MARCA_GET_LIST';
export const PRODUCTOS_MARCA_GET_LIST_SUCCESS =
  'PRODUCTOS_MARCA_GET_LIST_SUCCESS';
export const PRODUCTOS_MARCA_GET_LIST_ERROR = 'PRODUCTOS_MARCA_GET_LIST_ERROR';
export const PRODUCTOS_NO_ESTAN_ALMACEN_GET_LIST =
  'PRODUCTOS_NO_ESTAN_ALMACEN_GET_LIST';
export const PRODUCTOS_NO_ESTAN_ALMACEN_GET_LIST_SUCCESS =
  'PRODUCTOS_NO_ESTAN_ALMACEN_GET_LIST_SUCCESS';
export const PRODUCTOS_NO_ESTAN_ALMACEN_GET_LIST_ERROR =
  'PRODUCTOS_NO_ESTAN_ALMACEN_GET_LIST_ERROR';
export const PRODUCTOS_ALMACEN_ADD_ITEM = 'PRODUCTOS_ALMACEN_ADD_ITEM';
export const PRODUCTOS_ALMACEN_ADD_ITEM_SUCCESS =
  'PRODUCTOS_ALMACEN_ADD_ITEM_SUCCESS';
export const PRODUCTOS_ALMACEN_ADD_ITEM_ERROR =
  'PRODUCTOS_ALMACEN_ADD_ITEM_ERROR';
export const PRODUCTOS_NO_ESTAN_ORDEN_GET_LIST =
  'PRODUCTOS_NO_ESTAN_ORDEN_GET_LIST';
export const PRODUCTOS_NO_ESTAN_ORDEN_GET_LIST_SUCCESS =
  'PRODUCTOS_NO_ESTAN_ORDEN_GET_LIST_SUCCESS';
export const PRODUCTOS_NO_ESTAN_ORDEN_GET_LIST_ERROR =
  'PRODUCTOS_NO_ESTAN_ORDEN_GET_LIST_ERROR';
export const PRODUCTOS_ORDEN_GET_LIST = 'PRODUCTOS_ORDEN_GET_LIST';
export const PRODUCTOS_ORDEN_GET_LIST_SUCCESS =
  'PRODUCTOS_ORDEN_GET_LIST_SUCCESS';
export const PRODUCTOS_ORDEN_GET_LIST_ERROR = 'PRODUCTOS_ORDEN_GET_LIST_ERROR';
export const PRODUCTOS_ORDEN_UPD_ITEM = 'PRODUCTOS_ORDEN_UPD_ITEM';
export const PRODUCTOS_ORDEN_UPD_ITEM_SUCCESS =
  'PRODUCTOS_ORDEN_UPD_ITEM_SUCCESS';
export const PRODUCTOS_ORDEN_UPD_ITEM_ERROR = 'PRODUCTOS_ORDEN_UPD_ITEM_ERROR';
export const PRODUCTOS_ORDEN_ADD_ITEM = 'PRODUCTOS_ORDEN_ADD_ITEM';
export const PRODUCTOS_ORDEN_ADD_ITEM_SUCCESS =
  'PRODUCTOS_ORDEN_ADD_ITEM_SUCCESS';
export const PRODUCTOS_ORDEN_ADD_ITEM_ERROR = 'PRODUCTOS_ORDEN_ADD_ITEM_ERROR';
export const PRODUCTOS_CATEGORIA_GET_LIST = 'PRODUCTOS_CATEGORIA_GET_LIST';
export const PRODUCTOS_CATEGORIA_GET_LIST_SUCCESS =
  'PRODUCTOS_CATEGORIA_GET_LIST_SUCCESS';
export const PRODUCTOS_CATEGORIA_GET_LIST_ERROR =
  'PRODUCTOS_CATEGORIA_GET_LIST_ERROR';
export const PRODUCTOS_ALMACEN_VENTA_GET_LIST =
  'PRODUCTOS_ALMACEN_VENTA_GET_LIST';
export const PRODUCTOS_ALMACEN_VENTA_GET_LIST_SUCCESS =
  'PRODUCTOS_ALMACEN_VENTA_GET_LIST_SUCCESS';
export const PRODUCTOS_ALMACEN_VENTA_GET_LIST_ERROR =
  'PRODUCTOS_ALMACEN_VENTA_GET_LIST_ERROR';
export const PRODUCTOS_ORDEN_VENTA_GET_LIST = 'PRODUCTOS_ORDEN_VENTA_GET_LIST';
export const PRODUCTOS_ORDEN_VENTA_GET_LIST_SUCCESS =
  'PRODUCTOS_ORDEN_VENTA_GET_LIST_SUCCESS';
export const PRODUCTOS_ORDEN_VENTA_GET_LIST_ERROR =
  'PRODUCTOS_ORDEN_VENTA_GET_LIST_ERROR';
export const PRODUCTOS_MEJOR_VENDIDOS_GET_LIST =
  'PRODUCTOS_MEJOR_VENDIDOS_GET_LIST';
export const PRODUCTOS_MEJOR_VENDIDOS_GET_LIST_SUCCESS =
  'PRODUCTOS_MEJOR_VENDIDOS_GET_LIST_SUCCESS';
export const PRODUCTOS_MEJOR_VENDIDOS_GET_LIST_ERROR =
  'PRODUCTOS_MEJOR_VENDIDOS_GET_LIST_ERROR';

/* PRODUCTO APP */
export const PRODUCTO_GET_DETAILS = 'PRODUCTO_GET_DETAILS';
export const PRODUCTO_GET_DETAILS_SUCCESS = 'PRODUCTO_GET_DETAILS_SUCCESS';
export const PRODUCTO_GET_DETAILS_ERROR = 'PRODUCTO_GET_DETAILS_ERROR';
export const PRODUCTO_NEGOCIO_GET_DETAILS = 'PRODUCTO_NEGOCIO_GET_DETAILS';
export const PRODUCTO_NEGOCIO_GET_DETAILS_SUCCESS =
  'PRODUCTO_NEGOCIO_GET_DETAILS_SUCCESS';
export const PRODUCTO_NEGOCIO_GET_DETAILS_ERROR =
  'PRODUCTO_NEGOCIO_GET_DETAILS_ERROR';
export const PRODUCTO_ADD_PHOTO = 'PRODUCTO_ADD_PHOTO';
export const PRODUCTO_ADD_PHOTO_SUCCESS = 'PRODUCTO_ADD_PHOTO_SUCCESS';
export const PRODUCTO_ADD_PHOTO_ERROR = 'PRODUCTO_ADD_PHOTO_ERROR';

/* PROVEEDORES APP */
export const PROVEEDORES_GET_LIST = 'PROVEEDORES_GET_LIST';
export const PROVEEDORES_GET_LIST_SUCCESS = 'PROVEEDORES_GET_LIST_SUCCESS';
export const PROVEEDORES_GET_LIST_ERROR = 'PROVEEDORES_GET_LIST_ERROR';
export const PROVEEDORES_ADD_ITEM = 'PROVEEDORES_ADD_ITEM';
export const PROVEEDORES_ADD_ITEM_SUCCESS = 'PROVEEDORES_ADD_ITEM_SUCCESS';
export const PROVEEDORES_ADD_ITEM_ERROR = 'PROVEEDORES_ADD_ITEM_ERROR';
export const PROVEEDORES_ACTIVOS_GET_LIST = 'PROVEEDORES_ACTIVOS_GET_LIST';
export const PROVEEDORES_ACTIVOS_GET_LIST_SUCCESS =
  'PROVEEDORES_ACTIVOS_GET_LIST_SUCCESS';
export const PROVEEDORES_ACTIVOS_GET_LIST_ERROR =
  'PROVEEDORES_ACTIVOS_GET_LIST_ERROR';
export const PROVEEDORES_UPD_ITEM = 'PROVEEDORES_UPD_ITEM';
export const PROVEEDORES_UPD_ITEM_SUCCESS = 'PROVEEDORES_UPD_ITEM_SUCCESS';
export const PROVEEDORES_UPD_ITEM_ERROR = 'PROVEEDORES_UPD_ITEM_ERROR';

/* PROVEEDOR APP */
export const PROVEEDOR_GET_DETAILS = 'PROVEEDOR_GET_DETAILS';
export const PROVEEDOR_GET_DETAILS_SUCCESS = 'PROVEEDOR_GET_DETAILS_SUCCESS';
export const PROVEEDOR_GET_DETAILS_ERROR = 'PROVEEDOR_GET_DETAILS_ERROR';
export const PROVEEDOR_ADD_PHOTO = 'PROVEEDOR_ADD_PHOTO';
export const PROVEEDOR_ADD_PHOTO_SUCCESS = 'PROVEEDOR_ADD_PHOTO_SUCCESS';
export const PROVEEDOR_ADD_PHOTO_ERROR = 'PROVEEDOR_ADD_PHOTO_ERROR';

/* MARCAS APP */
export const MARCAS_GET_LIST = 'MARCAS_GET_LIST';
export const MARCAS_GET_LIST_SUCCESS = 'MARCAS_GET_LIST_SUCCESS';
export const MARCAS_GET_LIST_ERROR = 'MARCAS_GET_LIST_ERROR';
export const MARCAS_ADD_ITEM = 'MARCAS_ADD_ITEM';
export const MARCAS_ADD_ITEM_SUCCESS = 'MARCAS_ADD_ITEM_SUCCESS';
export const MARCAS_ADD_ITEM_ERROR = 'MARCAS_ADD_ITEM_ERROR';
export const MARCAS_UPD_ITEM = 'MARCAS_UPD_ITEM';
export const MARCAS_UPD_ITEM_SUCCESS = 'MARCAS_UPD_ITEM_SUCCESS';
export const MARCAS_UPD_ITEM_ERROR = 'MARCAS_UPD_ITEM_ERROR';
export const MARCAS_ACTIVAS_GET_LIST = 'MARCAS_ACTIVAS_GET_LIST';
export const MARCAS_ACTIVAS_GET_LIST_SUCCESS =
  'MARCAS_ACTIVAS_GET_LIST_SUCCESS';
export const MARCAS_ACTIVAS_GET_LIST_ERROR = 'MARCAS_ACTIVAS_GET_LIST_ERROR';

/* MARCA APP */
export const MARCA_GET_DETAILS = 'MARCA_GET_DETAILS';
export const MARCA_GET_DETAILS_SUCCESS = 'MARCA_GET_DETAILS_SUCCESS';
export const MARCA_GET_DETAILS_ERROR = 'MARCA_GET_DETAILS_ERROR';
export const MARCA_ADD_PHOTO = 'MARCA_ADD_PHOTO';
export const MARCA_ADD_PHOTO_SUCCESS = 'MARCA_ADD_PHOTO_SUCCESS';
export const MARCA_ADD_PHOTO_ERROR = 'MARCA_ADD_PHOTO_ERROR';

/* ALMACENES APP */
export const ALMACENES_ACTIVOS_GET_LIST = 'ALMACENES_ACTIVOS_GET_LIST';
export const ALMACENES_ACTIVOS_GET_LIST_SUCCESS =
  'ALMACENES_ACTIVOS_GET_LIST_SUCCESS';
export const ALMACENES_ACTIVOS_GET_LIST_ERROR =
  'ALMACENES_ACTIVOS_GET_LIST_ERROR';

/* ORDENES APP */
export const ORDENES_PRODUCTO_GET_LIST = 'ORDENES_PRODUCTO_GET_LIST';
export const ORDENES_PRODUCTO_GET_LIST_SUCCESS =
  'ORDENES_PRODUCTO_GET_LIST_SUCCESS';
export const ORDENES_PRODUCTO_GET_LIST_ERROR =
  'ORDENES_PRODUCTO_GET_LIST_ERROR';
export const ORDENES_ALMACEN_GET_LIST = 'ORDENES_ALMACEN_GET_LIST';
export const ORDENES_ALMACEN_GET_LIST_SUCCESS =
  'ORDENES_ALMACEN_GET_LIST_SUCCESS';
export const ORDENES_ALMACEN_GET_LIST_ERROR = 'ORDENES_ALMACEN_GET_LIST_ERROR';
export const ORDENES_PROVEEDOR_GET_LIST = 'ORDENES_PROVEEDOR_GET_LIST';
export const ORDENES_PROVEEDOR_GET_LIST_SUCCESS =
  'ORDENES_PROVEEDOR_GET_LIST_SUCCESS';
export const ORDENES_PROVEEDOR_GET_LIST_ERROR =
  'ORDENES_PROVEEDOR_GET_LIST_ERROR';
export const ORDENES_MARCA_GET_LIST = 'ORDENES_MARCA_GET_LIST';
export const ORDENES_MARCA_GET_LIST_SUCCESS = 'ORDENES_MARCA_GET_LIST_SUCCESS';
export const ORDENES_MARCA_GET_LIST_ERROR = 'ORDENES_MARCA_GET_LIST_ERROR';

/* ORDEN APP */
export const ORDEN_GET_DETAILS = 'ORDEN_GET_DETAILS';
export const ORDEN_GET_DETAILS_SUCCESS = 'ORDEN_GET_DETAILS_SUCCESS';
export const ORDEN_GET_DETAILS_ERROR = 'ORDEN_GET_DETAILS_ERROR';
export const ORDEN_ADD_PHOTO = 'ORDEN_ADD_PHOTO';
export const ORDEN_ADD_PHOTO_SUCCESS = 'ORDEN_ADD_PHOTO_SUCCESS';
export const ORDEN_ADD_PHOTO_ERROR = 'ORDEN_ADD_PHOTO_ERROR';
export const ORDEN_PRODUCTO_ADD_PHOTO = 'ORDEN_PRODUCTO_ADD_PHOTO';
export const ORDEN_PRODUCTO_ADD_PHOTO_SUCCESS =
  'ORDEN_PRODUCTO_ADD_PHOTO_SUCCESS';
export const ORDEN_PRODUCTO_ADD_PHOTO_ERROR = 'ORDEN_PRODUCTO_ADD_PHOTO_ERROR';
export const ORDEN_UPD_ESTADO = 'ORDEN_UPD_ESTADO';
export const ORDEN_UPD_ESTADO_SUCCESS = 'ORDEN_UPD_ESTADO_SUCCESS';
export const ORDEN_UPD_ESTADO_ERROR = 'ORDEN_UPD_ESTADO_ERROR';

/* TIPOS_ALMACEN APP */
export const TIPOS_ALMACEN_GET_LIST = 'TIPOS_ALMACEN_GET_LIST';
export const TIPOS_ALMACEN_GET_LIST_SUCCESS = 'TIPOS_ALMACEN_GET_LIST_SUCCESS';
export const TIPOS_ALMACEN_GET_LIST_ERROR = 'TIPOS_ALMACEN_GET_LIST_ERROR';

/* CLIENTES APP */
export const CLIENTES_GET_LIST = 'CLIENTES_GET_LIST';
export const CLIENTES_GET_LIST_SUCCESS = 'CLIENTES_GET_LIST_SUCCESS';
export const CLIENTES_GET_LIST_ERROR = 'CLIENTES_GET_LIST_ERROR';
export const CLIENTES_ADD_ITEM = 'CLIENTES_ADD_ITEM';
export const CLIENTES_ADD_ITEM_SUCCESS = 'CLIENTES_ADD_ITEM_SUCCESS';
export const CLIENTES_ADD_ITEM_ERROR = 'CLIENTES_ADD_ITEM_ERROR';
export const CLIENTES_UPD_ITEM = 'CLIENTES_UPD_ITEM';
export const CLIENTES_UPD_ITEM_SUCCESS = 'CLIENTES_UPD_ITEM_SUCCESS';
export const CLIENTES_UPD_ITEM_ERROR = 'CLIENTES_UPD_ITEM_ERROR';

/* CLIENTE APP */
export const CLIENTE_GET_DETAILS = 'CLIENTE_GET_DETAILS';
export const CLIENTE_GET_DETAILS_SUCCESS = 'CLIENTE_GET_DETAILS_SUCCESS';
export const CLIENTE_GET_DETAILS_ERROR = 'CLIENTE_GET_DETAILS_ERROR';
export const CLIENTE_ADD_PHOTO = 'CLIENTE_ADD_PHOTO';
export const CLIENTE_ADD_PHOTO_SUCCESS = 'CLIENTE_ADD_PHOTO_SUCCESS';
export const CLIENTE_ADD_PHOTO_ERROR = 'CLIENTE_ADD_PHOTO_ERROR';

/* USUARIO APP */
export const USUARIO_GET_DETAILS = 'USUARIO_GET_DETAILS';
export const USUARIO_GET_DETAILS_SUCCESS = 'USUARIO_GET_DETAILS_SUCCESS';
export const USUARIO_GET_DETAILS_ERROR = 'USUARIO_GET_DETAILS_ERROR';
export const USUARIO_ADD_PHOTO = 'USUARIO_ADD_PHOTO';
export const USUARIO_ADD_PHOTO_SUCCESS = 'USUARIO_ADD_PHOTO_SUCCESS';
export const USUARIO_ADD_PHOTO_ERROR = 'USUARIO_ADD_PHOTO_ERROR';

/* ORDENES VENTA APP */
export const ORDENES_VENTA_GET_LIST = 'ORDENES_VENTA_GET_LIST';
export const ORDENES_VENTA_GET_LIST_SUCCESS = 'ORDENES_VENTA_GET_LIST_SUCCESS';
export const ORDENES_VENTA_GET_LIST_ERROR = 'ORDENES_VENTA_GET_LIST_ERROR';
export const ORDENES_VENTA_ADD_ITEM = 'ORDENES_VENTA_ADD_ITEM';
export const ORDENES_VENTA_ADD_ITEM_SUCCESS = 'ORDENES_VENTA_ADD_ITEM_SUCCESS';
export const ORDENES_VENTA_ADD_ITEM_ERROR = 'ORDENES_VENTA_ADD_ITEM_ERROR';
export const ORDENES_VENTA_PRODUCTO_GET_LIST =
  'ORDENES_VENTA_PRODUCTO_GET_LIST';
export const ORDENES_VENTA_PRODUCTO_GET_LIST_SUCCESS =
  'ORDENES_VENTA_PRODUCTO_GET_LIST_SUCCESS';
export const ORDENES_VENTA_PRODUCTO_GET_LIST_ERROR =
  'ORDENES_VENTA_PRODUCTO_GET_LIST_ERROR';
export const ORDENES_VENTA_ALMACEN_GET_LIST = 'ORDENES_VENTA_ALMACEN_GET_LIST';
export const ORDENES_VENTA_ALMACEN_GET_LIST_SUCCESS =
  'ORDENES_VENTA_ALMACEN_GET_LIST_SUCCESS';
export const ORDENES_VENTA_ALMACEN_GET_LIST_ERROR =
  'ORDENES_VENTA_ALMACEN_GET_LIST_ERROR';
export const ORDENES_VENTA_PROVEEDOR_GET_LIST =
  'ORDENES_VENTA_PROVEEDOR_GET_LIST';
export const ORDENES_VENTA_PROVEEDOR_GET_LIST_SUCCESS =
  'ORDENES_VENTA_PROVEEDOR_GET_LIST_SUCCESS';
export const ORDENES_VENTA_PROVEEDOR_GET_LIST_ERROR =
  'ORDENES_VENTA_PROVEEDOR_GET_LIST_ERROR';
export const ORDENES_VENTA_MARCA_GET_LIST = 'ORDENES_VENTA_MARCA_GET_LIST';
export const ORDENES_VENTA_MARCA_GET_LIST_SUCCESS =
  'ORDENES_VENTA_MARCA_GET_LIST_SUCCESS';
export const ORDENES_VENTA_MARCA_GET_LIST_ERROR =
  'ORDENES_VENTA_MARCA_GET_LIST_ERROR';
export const ORDENES_VENTA_RECEPTOR_UPD_ITEM =
  'ORDENES_VENTA_RECEPTOR_UPD_ITEM';
export const ORDENES_VENTA_RECEPTOR_UPD_ITEM_SUCCESS =
  'ORDENES_VENTA_RECEPTOR_UPD_ITEM_SUCCESS';
export const ORDENES_VENTA_RECEPTOR_UPD_ITEM_ERROR =
  'ORDENES_VENTA_RECEPTOR_UPD_ITEM_ERROR';
export const ORDENES_VENTA_SEMANA_GET_LIST = 'ORDENES_VENTA_SEMANA_GET_LIST';
export const ORDENES_VENTA_SEMANA_GET_LIST_SUCCESS =
  'ORDENES_VENTA_SEMANA_GET_LIST_SUCCESS';
export const ORDENES_VENTA_SEMANA_GET_LIST_ERROR =
  'ORDENES_VENTA_SEMANA_GET_LIST_ERROR';
export const ORDENES_VENTA_SEMANA_MONTO_GET_LIST =
  'ORDENES_VENTA_SEMANA_MONTO_GET_LIST';
export const ORDENES_VENTA_SEMANA_MONTO_GET_LIST_SUCCESS =
  'ORDENES_VENTA_SEMANA_MONTO_GET_LIST_SUCCESS';
export const ORDENES_VENTA_SEMANA_MONTO_GET_LIST_ERROR =
  'ORDENES_VENTA_SEMANA_MONTO_GET_LIST_ERROR';

/* ORDEN APP */
export const ORDEN_VENTA_GET_DETAILS = 'ORDEN_VENTA_GET_DETAILS';
export const ORDEN_VENTA_GET_DETAILS_SUCCESS =
  'ORDEN_VENTA_GET_DETAILS_SUCCESS';
export const ORDEN_VENTA_GET_DETAILS_ERROR = 'ORDEN_VENTA_GET_DETAILS_ERROR';
export const ORDEN_VENTA_ADD_PHOTO = 'ORDEN_VENTA_ADD_PHOTO';
export const ORDEN_VENTA_ADD_PHOTO_SUCCESS = 'ORDEN_VENTA_ADD_PHOTO_SUCCESS';
export const ORDEN_VENTA_ADD_PHOTO_ERROR = 'ORDEN_VENTA_ADD_PHOTO_ERROR';
export const ORDEN_VENTA_PRODUCTO_ADD_PHOTO = 'ORDEN_VENTA_PRODUCTO_ADD_PHOTO';
export const ORDEN_VENTA_PRODUCTO_ADD_PHOTO_SUCCESS =
  'ORDEN_VENTA_PRODUCTO_ADD_PHOTO_SUCCESS';
export const ORDEN_VENTA_PRODUCTO_ADD_PHOTO_ERROR =
  'ORDEN_VENTA_PRODUCTO_ADD_PHOTO_ERROR';
export const ORDEN_VENTA_UPD_ESTADO = 'ORDEN_VENTA_UPD_ESTADO';
export const ORDEN_VENTA_UPD_ESTADO_SUCCESS = 'ORDEN_VENTA_UPD_ESTADO_SUCCESS';
export const ORDEN_VENTA_UPD_ESTADO_ERROR = 'ORDEN_VENTA_UPD_ESTADO_ERROR';

/* CATEGORIAS APP */
export const CATEGORIAS_GET_LIST = 'CATEGORIAS_GET_LIST';
export const CATEGORIAS_GET_LIST_SUCCESS = 'CATEGORIAS_GET_LIST_SUCCESS';
export const CATEGORIAS_GET_LIST_ERROR = 'CATEGORIAS_GET_LIST_ERROR';
export const CATEGORIAS_ADD_ITEM = 'CATEGORIAS_ADD_ITEM';
export const CATEGORIAS_ADD_ITEM_SUCCESS = 'CATEGORIAS_ADD_ITEM_SUCCESS';
export const CATEGORIAS_ADD_ITEM_ERROR = 'CATEGORIAS_ADD_ITEM_ERROR';
export const CATEGORIAS_UPD_ITEM = 'CATEGORIAS_UPD_ITEM';
export const CATEGORIAS_UPD_ITEM_SUCCESS = 'CATEGORIAS_UPD_ITEM_SUCCESS';
export const CATEGORIAS_UPD_ITEM_ERROR = 'CATEGORIAS_UPD_ITEM_ERROR';
export const CATEGORIAS_ACTIVAS_GET_LIST = 'CATEGORIAS_ACTIVAS_GET_LIST';
export const CATEGORIAS_ACTIVAS_GET_LIST_SUCCESS =
  'CATEGORIAS_ACTIVAS_GET_LIST_SUCCESS';
export const CATEGORIAS_ACTIVAS_GET_LIST_ERROR =
  'CATEGORIAS_ACTIVAS_GET_LIST_ERROR';
export const CATEGORIAS_TODAS_GET_LIST = 'CATEGORIAS_TODAS_GET_LIST';
export const CATEGORIAS_TODAS_GET_LIST_SUCCESS =
  'CATEGORIAS_TODAS_GET_LIST_SUCCESS';
export const CATEGORIAS_TODAS_GET_LIST_ERROR =
  'CATEGORIAS_TODAS_GET_LIST_ERROR';

/* CATEGORIA APP */
export const CATEGORIA_GET_DETAILS = 'CATEGORIA_GET_DETAILS';
export const CATEGORIA_GET_DETAILS_SUCCESS = 'CATEGORIA_GET_DETAILS_SUCCESS';
export const CATEGORIA_GET_DETAILS_ERROR = 'CATEGORIA_GET_DETAILS_ERROR';
export const CATEGORIA_ADD_PHOTO = 'CATEGORIA_ADD_PHOTO';
export const CATEGORIA_ADD_PHOTO_SUCCESS = 'CATEGORIA_ADD_PHOTO_SUCCESS';
export const CATEGORIA_ADD_PHOTO_ERROR = 'CATEGORIA_ADD_PHOTO_ERROR';

export * from './menu/actions';
export * from './settings/actions';
export * from './auth/actions';
export * from './productos/actions';
export * from './producto/actions';
export * from './proveedores/actions';
export * from './proveedor/actions';
export * from './marcas/actions';
export * from './marca/actions';
export * from './categorias/actions';
export * from './categoria/actions';
export * from './ordenes/actions';
export * from './orden/actions';
export * from './ordenesVenta/actions';
export * from './ordenVenta/actions';
export * from './tiposAlmacen/actions';
export * from './clientes/actions';
export * from './cliente/actions';
export * from './usuario/actions';
